// AUTO-GENERATED by BionicJS — do not edit
// This is a stub. The real client is generated into .bionicjs/api-client.ts at dev/build time.
// The Vite plugin resolves "#bionicjs-api" to .bionicjs/api-client.ts.
export const api = new Proxy({} as any, {
  get(_, path) {
    return new Proxy({} as any, {
      get(_, method) {
        return async (...args: any[]) => {
          const res = await fetch(`/api/${String(path)}`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(args[0]),
          });
          return res.json();
        };
      },
    });
  },
});
